CREATE OR REPLACE PROCEDURE FDB_NETEZZA_REFRESH AS
    V_SQL CLOB;

    PROCEDURE DROP_TABLE_IF_EXISTS(P_TABLE_NAME IN VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE ' || DBMS_ASSERT.QUALIFIED_SQL_NAME(P_TABLE_NAME) || ' PURGE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -942 THEN
                RAISE;
            END IF;
    END;
BEGIN
    /*============================================================*/
    /* External unzip / file discovery steps in SAS               */
    /* are environment-specific and are not executable in PL/SQL. */
    /*============================================================*/

    DROP_TABLE_IF_EXISTS('FDB_NETEZZA');
    DROP_TABLE_IF_EXISTS('MEDID');
    DROP_TABLE_IF_EXISTS('MEDID_DESC');

    /* Main NDC reference build */
    EXECUTE IMMEDIATE q'[
        CREATE TABLE FDB_NETEZZA AS
        SELECT
            N.NDC,
            LPAD(MID.MEDID, 8, '0') AS MEDID,
            MID2.MED_MEDID_DESC,
            MID2.MED_STRENGTH_UOM,
            LPAD(MID2.ROUTED_DOSAGE_FORM_MED_ID, 8, '0') AS ROUTED_DOSAGE_FORM_MED_ID,
            RDF.MED_ROUTED_DF_MED_ID_DESC AS ROUTED_DOSAGE_FORM_MEDID_DESC,
            LPAD(RDF.ROUTED_MED_ID, 8, '0') AS ROUTED_MED_ID,
            RM.MED_ROUTED_MED_ID_DESC,
            LPAD(MID2.GENERIC_MEDID, 8, '0') AS GENERIC_MEDID,
            LPAD(RG.ROUTED_GEN_ID, 8, '0') AS ROUTED_GEN_ID,
            RGD.ROUTED_GEN_DESC,
            CASE WHEN N.DADDNC <> '00000000' THEN TO_DATE(N.DADDNC, 'YYYYMMDD') END AS DATE_NDC_ADDED,
            CASE WHEN N.DUPDC <> '00000000' THEN TO_DATE(N.DUPDC, 'YYYYMMDD') END AS DATE_NDC_UPDATED,
            CASE WHEN N.OBSDTEC <> '00000000' THEN TO_DATE(N.OBSDTEC, 'YYYYMMDD') END AS DATE_NDC_OBSOLETE,
            N.LN AS LABEL_NAME,
            N.LN60 AS LABEL_NAME60,
            N.BN AS BRAND_NAME,
            GEN.GNN60 AS GENERIC_NAME,
            LPAD(G.GCN, 5, '0') AS GCN,
            LPAD(GM.TC, 2, '0') AS STANDARD_TC_CODE,
            TC.TC_DESC AS STANDARD_TC_DESC,
            GM.HIC3 AS SPECIFIC_TC_CODE,
            HIC.HIC3_DESC AS SPECIFIC_TC_DESC,
            LPAD(N.GCN_SEQNO, 6, '0') AS CLINICAL_FORMULATION_ID,
            LPAD(GM.HICL_SEQNO, 6, '0') AS HICL_SEQNO,
            SUBSTR(LPAD(AHFS.AHFS8, 8, '0'), 1, 6) AS AHFS6,
            AHFS6.AHFS_DESC AS AHFS6_DESC,
            LPAD(AHFS.AHFS8, 8, '0') AS AHFS,
            AHFS2.AHFS_DESC,
            COALESCE(ATC.ATC, '') AS ATC,
            COALESCE(ATC_DESC.ATC_DESC, '') AS ATC_DESC,
            GM.GTC AS GENERIC_TX_CLASS_CODE,
            GTC.GTC_DESC AS GENERIC_TX_CLASS_DESC,
            N.CL AS DRUG_CLASS,
            CASE WHEN N.CL='F' THEN 'Product labeling indicates prescription or physician supervision required for use.'
                 WHEN N.CL='O' THEN 'Product has no labeling indicating dispensing limitations.'
                 ELSE ' ' END AS DRUG_CLASS_DESC,
            LPAD(ETC.ETC_ID, 8, '0') AS ETC_ID,
            ETC2.ETC_NAME,
            N.LBLRID AS LABELER_ID,
            MFR.MFG AS MANUFACTURER,
            MFR.LBLRIND AS LABELER_IND,
            N.DF AS DRUG_FORM_CODE,
            CASE WHEN N.DF=1 THEN 'each (tablets, kits, etc.)'
                 WHEN N.DF=2 THEN 'milliliters (liquids)'
                 WHEN N.DF=3 THEN 'grams (solids)'
                 ELSE '' END AS DRUG_FORM_DESC,
            GM.GCDF AS DOSE_FORM_CODE,
            DOSE.DOSE_DESC AS DOSE_FORM_DESC,
            DOSE.DOSE,
            GM.GCRT AS ROUTE_CODE,
            RT.RT AS ROUTE,
            RT.GCRT_DESC AS ROUTE_DESC,
            GM.STR AS DRUG_STRENGTH_DESC,
            GM.STR60 AS DRUG_STRENGTH_DESC60,
            STR.STRNUM AS STRENGTH_NUMBER,
            STR.STRUN50 AS STRENGTH_UNIT,
            STR.VOLNUM AS VOLUME_NUMBER,
            STR.VOLUN50 AS VOLUME_UNIT,
            N.PS AS PACKAGE_SIZE,
            GM.DCC AS DRUG_CATEGORY_CODE,
            DC.DCC_DESC AS DRUG_CATEGORY_DESC,
            N.DEA AS DEA_CODE,
            CASE WHEN N.DEA=0 THEN 'No control'
                 WHEN N.DEA=1 THEN 'LSD, Heroin, Marijuana - Research only'
                 WHEN N.DEA=2 THEN 'Morphine, Meperidine, Amphetamines, etc., most potential for abuse'
                 WHEN N.DEA=3 THEN 'Aspirin/Codeine, etc., less abused'
                 WHEN N.DEA=4 THEN 'Diazepam, etc., potential abuse'
                 WHEN N.DEA=5 THEN 'Controlled sale by pharmacy only'
                 ELSE '' END AS DEA_DESC,
            N.OBC AS ORANGE_BOOK_CODE,
            OBC.OBC_DESC AS ORANGE_BOOK_DESC,
            OBC2.OBC_DESC AS ORANGE_BOOK_DESC2,
            COD58.NDC_ATTRIBUTE_VALUE AS COD_STATUS_CODE,
            COD58DESC.NDC_ATTRIBUTE_VALUE_DSC AS COD_STATUS_DESC,
            CASE WHEN COD59.NDC_ATTRIBUTE_VALUE <> '00000000' THEN TO_DATE(COD59.NDC_ATTRIBUTE_VALUE, 'YYYYMMDD') END AS COD_STATUS_EFFECTIVE_DATE,
            N.MAINT AS MAINTENANCE_DRUG_IND,
            CASE WHEN N.MAINT='1' THEN 'Maintenance drug' ELSE 'Not a maintenance drug' END AS MAINTENANCE_DRUG_DESC,
            N.NDCGI1 AS SS_MS_IND,
            CASE WHEN N.NDCGI1='1' THEN 'Multiple source'
                 WHEN N.NDCGI1='2' THEN 'Single source'
                 ELSE '' END AS SS_MS_DESC,
            N.GPI AS GENERIC_PRICING_IND,
            N.GTI AS THERAPEUTIC_EQUIVALENCE_IND,
            CASE WHEN N.GTI='0' THEN 'Non-drug item, such as medical supplies and bulk chemicals'
                 WHEN N.GTI='1' THEN 'Orange Book B-rated drug product'
                 WHEN N.GTI='2' THEN 'Single source'
                 WHEN N.GTI='3' THEN 'Orange Book A-rated drug product'
                 WHEN N.GTI='4' THEN 'Product not listed in the Orange Book'
                 ELSE ' ' END AS THERAPEUTIC_EQUIVALENCE_DESC,
            CASE WHEN N.GNI='0' THEN '0'
                 WHEN N.GNI='1' THEN '1'
                 WHEN N.GNI='2' AND N.INNOV='1' THEN '2'
                 WHEN FDA.NDA_IND='1' THEN '2'
                 WHEN FDA.ANDA_IND='1' THEN '1'
                 WHEN N.INNOV='0' AND N.REPACK='0' THEN '1'
                 WHEN N.INNOV='0' AND N.REPACK='1' THEN '2'
                 ELSE ' ' END AS DERIVED_GENERIC_PRICING_IND,
            CASE WHEN N.GNI='0' THEN '1'
                 WHEN N.GNI='1' THEN '2'
                 WHEN N.GNI='2' AND N.INNOV='1' THEN '3'
                 WHEN FDA.NDA_IND='1' THEN '4'
                 WHEN FDA.ANDA_IND='1' THEN '5'
                 WHEN N.INNOV='0' AND N.REPACK='0' THEN '6'
                 WHEN N.INNOV='0' AND N.REPACK='1' THEN '7'
                 ELSE ' ' END AS DERIVED_GPI_RULE,
            N.GNI AS GENERIC_NAME_IND,
            N.STPK AS STANDARD_PACKAGE_IND,
            N.SHLF_PCK AS SHELF_PACK,
            N.PD AS PACKAGE_DESC,
            N.UU AS UNIT_USE_IND,
            N.UD AS UNIT_DOSE_IND,
            N.INNOV AS INNOVATOR_IND,
            N.REPACK AS REPACKAGER_IND,
            FDA.NDA_IND,
            FDA.ANDA_IND,
            FDA.LISTING_SEQ_NO,
            FDA.TRADENAME,
            CASE WHEN BLA1.BLA_DATE IS NOT NULL THEN TO_DATE(BLA1.BLA_DATE, 'YYYYMMDD') END AS BLA_DATE,
            CASE WHEN BLA2.BLA_DATE IS NOT NULL THEN TO_DATE(BLA2.BLA_DATE, 'YYYYMMDD') END AS BLA_DATE2,
            WAC1.NPT_PRICEX AS WAC_UNIT_PRICE1,
            CASE WHEN WAC1.NPT_DATEC IS NOT NULL THEN TO_DATE(WAC1.NPT_DATEC, 'YYYYMMDD') END AS WAC_EFFECTIVE_DATE1,
            WAC2.NPT_PRICEX AS WAC_UNIT_PRICE2,
            CASE WHEN WAC2.NPT_DATEC IS NOT NULL THEN TO_DATE(WAC2.NPT_DATEC, 'YYYYMMDD') END AS WAC_EFFECTIVE_DATE2,
            WAC3.NPT_PRICEX AS WAC_UNIT_PRICE3,
            CASE WHEN WAC3.NPT_DATEC IS NOT NULL THEN TO_DATE(WAC3.NPT_DATEC, 'YYYYMMDD') END AS WAC_EFFECTIVE_DATE3,
            WAC4.NPT_PRICEX AS WAC_UNIT_PRICE4,
            CASE WHEN WAC4.NPT_DATEC IS NOT NULL THEN TO_DATE(WAC4.NPT_DATEC, 'YYYYMMDD') END AS WAC_EFFECTIVE_DATE4,
            WAC5.NPT_PRICEX AS WAC_UNIT_PRICE5,
            CASE WHEN WAC5.NPT_DATEC IS NOT NULL THEN TO_DATE(WAC5.NPT_DATEC, 'YYYYMMDD') END AS WAC_EFFECTIVE_DATE5,
            WAC6.NPT_PRICEX AS WAC_UNIT_PRICE6,
            CASE WHEN WAC6.NPT_DATEC IS NOT NULL THEN TO_DATE(WAC6.NPT_DATEC, 'YYYYMMDD') END AS WAC_EFFECTIVE_DATE6,
            WAC7.NPT_PRICEX AS WAC_UNIT_PRICE7,
            CASE WHEN WAC7.NPT_DATEC IS NOT NULL THEN TO_DATE(WAC7.NPT_DATEC, 'YYYYMMDD') END AS WAC_EFFECTIVE_DATE7,
            WAC8.NPT_PRICEX AS WAC_UNIT_PRICE8,
            CASE WHEN WAC8.NPT_DATEC IS NOT NULL THEN TO_DATE(WAC8.NPT_DATEC, 'YYYYMMDD') END AS WAC_EFFECTIVE_DATE8,
            NADAC1.NPT_PRICEX AS NADAC_UNIT_PRICE1,
            NADAC1.NADAC_TYPE AS NADAC_TYPE1,
            CASE WHEN NADAC1.NPT_DATEC IS NOT NULL THEN TO_DATE(NADAC1.NPT_DATEC, 'YYYYMMDD') END AS NADAC_EFFECTIVE_DATE1,
            NADAC2.NPT_PRICEX AS NADAC_UNIT_PRICE2,
            NADAC2.NADAC_TYPE AS NADAC_TYPE2,
            CASE WHEN NADAC2.NPT_DATEC IS NOT NULL THEN TO_DATE(NADAC2.NPT_DATEC, 'YYYYMMDD') END AS NADAC_EFFECTIVE_DATE2,
            NADAC3.NPT_PRICEX AS NADAC_UNIT_PRICE3,
            NADAC3.NADAC_TYPE AS NADAC_TYPE3,
            CASE WHEN NADAC3.NPT_DATEC IS NOT NULL THEN TO_DATE(NADAC3.NPT_DATEC, 'YYYYMMDD') END AS NADAC_EFFECTIVE_DATE3,
            NADAC4.NPT_PRICEX AS NADAC_UNIT_PRICE4,
            NADAC4.NADAC_TYPE AS NADAC_TYPE4,
            CASE WHEN NADAC4.NPT_DATEC IS NOT NULL THEN TO_DATE(NADAC4.NPT_DATEC, 'YYYYMMDD') END AS NADAC_EFFECTIVE_DATE4,
            NADAC5.NPT_PRICEX AS NADAC_UNIT_PRICE5,
            NADAC5.NADAC_TYPE AS NADAC_TYPE5,
            CASE WHEN NADAC5.NPT_DATEC IS NOT NULL THEN TO_DATE(NADAC5.NPT_DATEC, 'YYYYMMDD') END AS NADAC_EFFECTIVE_DATE5,
            NADAC6.NPT_PRICEX AS NADAC_UNIT_PRICE6,
            NADAC6.NADAC_TYPE AS NADAC_TYPE6,
            CASE WHEN NADAC6.NPT_DATEC IS NOT NULL THEN TO_DATE(NADAC6.NPT_DATEC, 'YYYYMMDD') END AS NADAC_EFFECTIVE_DATE6,
            NADAC7.NPT_PRICEX AS NADAC_UNIT_PRICE7,
            NADAC7.NADAC_TYPE AS NADAC_TYPE7,
            CASE WHEN NADAC7.NPT_DATEC IS NOT NULL THEN TO_DATE(NADAC7.NPT_DATEC, 'YYYYMMDD') END AS NADAC_EFFECTIVE_DATE7,
            NADAC8.NPT_PRICEX AS NADAC_UNIT_PRICE8,
            NADAC8.NADAC_TYPE AS NADAC_TYPE8,
            CASE WHEN NADAC8.NPT_DATEC IS NOT NULL THEN TO_DATE(NADAC8.NPT_DATEC, 'YYYYMMDD') END AS NADAC_EFFECTIVE_DATE8,
            FUL1.NPT_PRICEX AS FUL_UNIT_PRICE1,
            CASE WHEN FUL1.NPT_DATEC IS NOT NULL THEN TO_DATE(FUL1.NPT_DATEC, 'YYYYMMDD') END AS FUL_EFFECTIVE_DATE1,
            FUL2.NPT_PRICEX AS FUL_UNIT_PRICE2,
            CASE WHEN FUL2.NPT_DATEC IS NOT NULL THEN TO_DATE(FUL2.NPT_DATEC, 'YYYYMMDD') END AS FUL_EFFECTIVE_DATE2,
            FUL3.NPT_PRICEX AS FUL_UNIT_PRICE3,
            CASE WHEN FUL3.NPT_DATEC IS NOT NULL THEN TO_DATE(FUL3.NPT_DATEC, 'YYYYMMDD') END AS FUL_EFFECTIVE_DATE3,
            FUL4.NPT_PRICEX AS FUL_UNIT_PRICE4,
            CASE WHEN FUL4.NPT_DATEC IS NOT NULL THEN TO_DATE(FUL4.NPT_DATEC, 'YYYYMMDD') END AS FUL_EFFECTIVE_DATE4,
            FUL5.NPT_PRICEX AS FUL_UNIT_PRICE5,
            CASE WHEN FUL5.NPT_DATEC IS NOT NULL THEN TO_DATE(FUL5.NPT_DATEC, 'YYYYMMDD') END AS FUL_EFFECTIVE_DATE5,
            FUL6.NPT_PRICEX AS FUL_UNIT_PRICE6,
            CASE WHEN FUL6.NPT_DATEC IS NOT NULL THEN TO_DATE(FUL6.NPT_DATEC, 'YYYYMMDD') END AS FUL_EFFECTIVE_DATE6,
            FUL7.NPT_PRICEX AS FUL_UNIT_PRICE7,
            CASE WHEN FUL7.NPT_DATEC IS NOT NULL THEN TO_DATE(FUL7.NPT_DATEC, 'YYYYMMDD') END AS FUL_EFFECTIVE_DATE7,
            FUL8.NPT_PRICEX AS FUL_UNIT_PRICE8,
            CASE WHEN FUL8.NPT_DATEC IS NOT NULL THEN TO_DATE(FUL8.NPT_DATEC, 'YYYYMMDD') END AS FUL_EFFECTIVE_DATE8
        FROM RNDC14_NDC_MSTR N
        LEFT JOIN RMINDC1_NDC_MEDID MID ON N.NDC = MID.NDC
        LEFT JOIN RMIID1_MED MID2 ON MID.MEDID = MID2.MEDID
        LEFT JOIN RRTGNND0_ROUTED_GEN_NDC_LINK RG ON N.NDC = RG.NDC
        LEFT JOIN RMIDFID1_ROUTED_DOSE_FORM_MED RDF ON MID2.ROUTED_DOSAGE_FORM_MED_ID = RDF.ROUTED_DOSAGE_FORM_MED_ID
        LEFT JOIN RMIRMID1_ROUTED_MED RM ON RDF.ROUTED_MED_ID = RM.ROUTED_MED_ID
        LEFT JOIN RRTGN0_ROUTED_GEN_MSTR RGD ON RG.ROUTED_GEN_ID = RGD.ROUTED_GEN_ID
        LEFT JOIN RLBLRID3_LBLR_DESC MFR ON N.LBLRID = MFR.LBLRID
        LEFT JOIN RGCN0_GCN_GCNSEQNO_LINK G ON N.GCN_SEQNO = G.GCN_SEQNO
        LEFT JOIN RGCNSEQ4_GCNSEQNO_MSTR GM ON N.GCN_SEQNO = GM.GCN_SEQNO
        LEFT JOIN RATCGC0_ATC_GCNSEQNO_LINK ATC ON N.GCN_SEQNO = ATC.GCN_SEQNO
        LEFT JOIN RATCD0_ATC_DESC ATC_DESC ON ATC.ATC = ATC_DESC.ATC
        LEFT JOIN RHICLSQ1_HICLSEQNO_MSTR GEN ON GM.HICL_SEQNO = GEN.HICL_SEQNO
        LEFT JOIN RGTCD0_GEN_THERAP_CLASS_DESC GTC ON GM.GTC = GTC.GTC
        LEFT JOIN RSTR1_STRNGTH_DESC STR ON GM.STR60 = STR.STR60
        LEFT JOIN RDOSED2_DOSE_DESC DOSE ON GM.GCDF = DOSE.GCDF
        LEFT JOIN RROUTED3_ROUTE_DESC RT ON GM.GCRT = RT.GCRT
        LEFT JOIN RDCCD0_DRUG_CAT_DESC DC ON GM.DCC = DC.DCC
        LEFT JOIN ROBCD0_OBC_DESC OBC ON N.OBC = OBC.OBC AND OBC.OBC_SN = 1
        LEFT JOIN ROBCD0_OBC_DESC OBC2 ON N.OBC = OBC2.OBC AND OBC2.OBC_SN = 2
        LEFT JOIN RAPPLSL0_FDA_NDC_NDA_ANDA FDA ON N.NDC = FDA.NDC
        LEFT JOIN RTCD0_STD_THERAP_CLASS_DESC TC ON GM.TC = TC.TC
        LEFT JOIN RHIC3D3_HIC_THERAP_CLASS_DESC HIC ON GM.HIC3 = HIC.HIC3
        LEFT JOIN RAHFSGC1_GCNSEQNO_LINK AHFS ON N.GCN_SEQNO = AHFS.GCN_SEQNO AND AHFS.AHFS_REL = 1
        LEFT JOIN RAHFSD1_DESC AHFS2 ON AHFS.AHFS8 = AHFS2.AHFS8
        LEFT JOIN RAHFSD1_DESC AHFS6 ON SUBSTR(LPAD(AHFS.AHFS8, 8, '0'), 1, 6) || '00' = AHFS6.AHFS8
        LEFT JOIN RETCNDC0_ETC_NDC ETC ON N.NDC = ETC.NDC AND ETC.ETC_COMMON_USE_IND = 1
        LEFT JOIN RETCTBL0_ETC_ID ETC2 ON ETC.ETC_ID = ETC2.ETC_ID
        LEFT JOIN (SELECT NDC, NDC_ATTRIBUTE_VALUE AS BLA_DATE, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NDC_ATTRIBUTE_VALUE) AS BLA_SEQ FROM RNDCAT0_NDC_ATTRIBUTE WHERE NDC_ATTRIBUTE_TYPE_CD = 19) BLA1 ON N.NDC = BLA1.NDC AND BLA1.BLA_SEQ = 1
        LEFT JOIN (SELECT NDC, NDC_ATTRIBUTE_VALUE AS BLA_DATE, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NDC_ATTRIBUTE_VALUE) AS BLA_SEQ FROM RNDCAT0_NDC_ATTRIBUTE WHERE NDC_ATTRIBUTE_TYPE_CD = 19) BLA2 ON N.NDC = BLA2.NDC AND BLA2.BLA_SEQ = 2
        LEFT JOIN (SELECT * FROM RNDCAT0_NDC_ATTRIBUTE WHERE NDC_ATTRIBUTE_TYPE_CD = 58) COD58 ON N.NDC = COD58.NDC
        LEFT JOIN RNDCVD0_NDC_ATTRIBUTE_VALU_DSC COD58DESC ON COD58.NDC_ATTRIBUTE_TYPE_CD = COD58DESC.NDC_ATTRIBUTE_TYPE_CD AND COD58.NDC_ATTRIBUTE_VALUE = COD58DESC.NDC_ATTRIBUTE_VALUE
        LEFT JOIN (SELECT * FROM RNDCAT0_NDC_ATTRIBUTE WHERE NDC_ATTRIBUTE_TYPE_CD = 59) COD59 ON N.NDC = COD59.NDC
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS WAC_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='09') WAC1 ON N.NDC = WAC1.NDC AND WAC1.WAC_SEQ = 1
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS WAC_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='09') WAC2 ON N.NDC = WAC2.NDC AND WAC2.WAC_SEQ = 2
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS WAC_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='09') WAC3 ON N.NDC = WAC3.NDC AND WAC3.WAC_SEQ = 3
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS WAC_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='09') WAC4 ON N.NDC = WAC4.NDC AND WAC4.WAC_SEQ = 4
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS WAC_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='09') WAC5 ON N.NDC = WAC5.NDC AND WAC5.WAC_SEQ = 5
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS WAC_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='09') WAC6 ON N.NDC = WAC6.NDC AND WAC6.WAC_SEQ = 6
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS WAC_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='09') WAC7 ON N.NDC = WAC7.NDC AND WAC7.WAC_SEQ = 7
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS WAC_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='09') WAC8 ON N.NDC = WAC8.NDC AND WAC8.WAC_SEQ = 8
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, NADAC_TYPE, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS NADAC_SEQ FROM FDB_NADAC) NADAC1 ON N.NDC = NADAC1.NDC AND NADAC1.NADAC_SEQ = 1
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, NADAC_TYPE, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS NADAC_SEQ FROM FDB_NADAC) NADAC2 ON N.NDC = NADAC2.NDC AND NADAC2.NADAC_SEQ = 2
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, NADAC_TYPE, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS NADAC_SEQ FROM FDB_NADAC) NADAC3 ON N.NDC = NADAC3.NDC AND NADAC3.NADAC_SEQ = 3
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, NADAC_TYPE, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS NADAC_SEQ FROM FDB_NADAC) NADAC4 ON N.NDC = NADAC4.NDC AND NADAC4.NADAC_SEQ = 4
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, NADAC_TYPE, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS NADAC_SEQ FROM FDB_NADAC) NADAC5 ON N.NDC = NADAC5.NDC AND NADAC5.NADAC_SEQ = 5
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, NADAC_TYPE, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS NADAC_SEQ FROM FDB_NADAC) NADAC6 ON N.NDC = NADAC6.NDC AND NADAC6.NADAC_SEQ = 6
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, NADAC_TYPE, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS NADAC_SEQ FROM FDB_NADAC) NADAC7 ON N.NDC = NADAC7.NDC AND NADAC7.NADAC_SEQ = 7
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, NADAC_TYPE, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS NADAC_SEQ FROM FDB_NADAC) NADAC8 ON N.NDC = NADAC8.NDC AND NADAC8.NADAC_SEQ = 8
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS FUL_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='23') FUL1 ON N.NDC = FUL1.NDC AND FUL1.FUL_SEQ = 1
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS FUL_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='23') FUL2 ON N.NDC = FUL2.NDC AND FUL2.FUL_SEQ = 2
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS FUL_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='23') FUL3 ON N.NDC = FUL3.NDC AND FUL3.FUL_SEQ = 3
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS FUL_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='23') FUL4 ON N.NDC = FUL4.NDC AND FUL4.FUL_SEQ = 4
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS FUL_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='23') FUL5 ON N.NDC = FUL5.NDC AND FUL5.FUL_SEQ = 5
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS FUL_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='23') FUL6 ON N.NDC = FUL6.NDC AND FUL6.FUL_SEQ = 6
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS FUL_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='23') FUL7 ON N.NDC = FUL7.NDC AND FUL7.FUL_SEQ = 7
        LEFT JOIN (SELECT NDC, NPT_PRICEX, NPT_DATEC, ROW_NUMBER() OVER (PARTITION BY NDC ORDER BY NDC, NPT_DATEC DESC) AS FUL_SEQ FROM RNP2_NDC_PRICE WHERE NPT_TYPE='23') FUL8 ON N.NDC = FUL8.NDC AND FUL8.FUL_SEQ = 8
    ]';

    EXECUTE IMMEDIATE q'[
        CREATE TABLE MEDID AS
        SELECT *, SYSTIMESTAMP AS LOAD_DATE
        FROM RX_DATA.RMINDC1_NDC_MEDID
    ]';

    EXECUTE IMMEDIATE q'[
        CREATE TABLE MEDID_DESC AS
        SELECT *, SYSTIMESTAMP AS LOAD_DATE
        FROM RX_DATA.RMIID1_MED
    ]';

    COMMIT;
END FDB_NETEZZA_REFRESH;
/
