
CREATE OR REPLACE PROCEDURE MONTHLY_DAA74958_GLP_PA AS
    PROCEDURE DROP_TABLE_IF_EXISTS(P_TABLE_NAME IN VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE ' || DBMS_ASSERT.QUALIFIED_SQL_NAME(P_TABLE_NAME) || ' PURGE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -942 THEN RAISE; END IF;
    END;
BEGIN
    DROP_TABLE_IF_EXISTS('ACCEL_DAA74958');
    DROP_TABLE_IF_EXISTS('DUPCK_ACCEL_DAA74958');
    DROP_TABLE_IF_EXISTS('BMI_BASE');
    DROP_TABLE_IF_EXISTS('BMI_TMP');
    DROP_TABLE_IF_EXISTS('RPTOUT_DTL');
    DROP_TABLE_IF_EXISTS('RPTOUT_SUM');

    EXECUTE IMMEDIATE q'[
        CREATE TABLE ACCEL_DAA74958 AS
        SELECT DISTINCT
            CASE WHEN B.NDC IS NULL THEN 'Non-GLP1: DM' ELSE 'Drug Type 1' END AS drug_type1,
            CASE WHEN B.NDC IS NULL THEN 'Non-GLP1: DM' ELSE 'Drug Type2' END AS drug_type2,
            AA.COMMENTS, AA.LOB, AA.LOB2, AA.RECEIVED_DATE, AA.EFFECTUATION__DATE,
            AA.REQUEST_TYPE, AA.INTAKE_TYPE, AA.MEMBER_ID, AA.PERSON_NUMBER,
            AA.MEMBER_FIRST_NAME, AA.MEMBER_LAST_NAME, AA.MEMBER_DATE_OF_BIRTH,
            AA.AUTHORIZATION_NUMBER, AA.NDC_NUMBER, AA.LABEL_NAME, AA.CASE_NUMBER,
            UPPER(AA.CASE_STATUS) AS CASE_STATUS,
            AA.STATUS_REASON_DESCRIPTION, AA.REQUEST_REASON_DESCRIPTION, AA.MODC_CODE,
            AA.COVERAGE_CODE_1, AA.COVERAGE_CODE_2, AA.ATTRIBUTE_6, AA.ATTRIBUTE_7,
            AA.CVS_CARRIER, AA.CVS_ACCOUNT, AA.CVS_GRP, AA.CUSTOMER_NUMBER,
            AA.CLIENT_NUMBER, AA.GROUP_CODE, AA.FORMULARY, AA.SOURCE_FILE
        FROM RX_DATA.AUTHACCEL AA
        LEFT JOIN A.R12_DIAB_DRUGS B ON AA.NDC_NUMBER = B.NDC
        WHERE TRUNC(AA.RECEIVED_DATE) BETWEEN DATE '2023-01-01' AND DATE '2023-01-31'
          AND UPPER(AA.CASE_STATUS) IN ('APPROVED','DENIED')
          AND AA.NDC_NUMBER IN (
              SELECT NDC FROM A.R12_DIAB_DRUGS
              UNION
              SELECT NDC FROM RX_DATA.MEDISPAN WHERE GPI4 IN (SELECT DISTINCT GPI4 FROM A.R12_DIAB_DRUGS_GPI4)
          )
    ]';

    EXECUTE IMMEDIATE q'[
        CREATE TABLE DUPCK_ACCEL_DAA74958 AS
        SELECT *
        FROM ACCEL_DAA74958
        WHERE CASE_NUMBER IN (SELECT CASE_NUMBER FROM ACCEL_DAA74958 GROUP BY CASE_NUMBER HAVING COUNT(*) > 1)
        ORDER BY CASE_NUMBER, RECEIVED_DATE
    ]';

    EXECUTE IMMEDIATE q'[
        CREATE TABLE BMI_BASE AS
        SELECT *
        FROM ACCEL_DAA74958
        WHERE (INSTR(COMMENTS,'BMI') > 0 OR INSTR(UPPER(COMMENTS),'BMI ') > 0 OR INSTR(UPPER(COMMENTS),' BMI') > 0)
          AND drug_type1 IN ('GLP-1: DM w WL','GLP-1: WL only')
    ]';

    EXECUTE IMMEDIATE q'[
        CREATE TABLE BMI_TMP AS
        SELECT
            B.*,
            COALESCE(
                TO_NUMBER(REGEXP_SUBSTR(SUBSTR(B.COMMENTS, INSTR(B.COMMENTS,'BMI'), 20), '[0-9]+(\.[0-9]+)?')),
                TO_NUMBER(REGEXP_SUBSTR(SUBSTR(B.COMMENTS, INSTR(UPPER(B.COMMENTS),'BMI '), 20), '[0-9]+(\.[0-9]+)?')),
                TO_NUMBER(REGEXP_SUBSTR(SUBSTR(B.COMMENTS, INSTR(UPPER(B.COMMENTS),' BMI'), 20), '[0-9]+(\.[0-9]+)?'))
            ) AS BMI_FNL,
            CASE
                WHEN REGEXP_LIKE(UPPER(B.COMMENTS), 'HYPERTENSION|DYSLIPIDEMIA|PCOS|PREDIABETES|DIABETES|STROKE|NASH|OSTEOARTHRITIS|CAD|CVD|HTN|DM|OA|OSA|MI|CORONARY ARTERY DISEASE|SLEEP APNEA CURRENTLY BEING TREATED WITH CPAP|METABOLIC SYNDROME')
                THEN 'Y'
            END AS CO_MORBID,
            CASE
                WHEN COALESCE(
                    TO_NUMBER(REGEXP_SUBSTR(SUBSTR(B.COMMENTS, INSTR(B.COMMENTS,'BMI'), 20), '[0-9]+(\.[0-9]+)?')),
                    TO_NUMBER(REGEXP_SUBSTR(SUBSTR(B.COMMENTS, INSTR(UPPER(B.COMMENTS),'BMI '), 20), '[0-9]+(\.[0-9]+)?')),
                    TO_NUMBER(REGEXP_SUBSTR(SUBSTR(B.COMMENTS, INSTR(UPPER(B.COMMENTS),' BMI'), 20), '[0-9]+(\.[0-9]+)?'))
                ) BETWEEN 27 AND 29.999999
                THEN 'Y'
            END AS OVERWEIGHT
        FROM BMI_BASE B
    ]';

    EXECUTE IMMEDIATE q'[
        CREATE TABLE RPTOUT_DTL AS
        SELECT CASE_NUMBER, CASE_STATUS, REQUEST_REASON_DESCRIPTION, MEMBER_ID, PERSON_NUMBER,
               MEMBER_FIRST_NAME, MEMBER_LAST_NAME, MEMBER_DATE_OF_BIRTH, AUTHORIZATION_NUMBER,
               NDC_NUMBER, LABEL_NAME, drug_type1, BMI_FNL,
               CASE WHEN BMI_FNL >= 30 THEN 'Y' ELSE ' ' END AS OBESE,
               CASE WHEN OVERWEIGHT = 'Y' AND CO_MORBID IS NOT NULL THEN 'Y' ELSE ' ' END AS OVERWT_COMORBID,
               OVERWEIGHT, CO_MORBID, COMMENTS
        FROM BMI_TMP
    ]';

    EXECUTE IMMEDIATE q'[
        CREATE TABLE RPTOUT_SUM AS
        SELECT drug_type1,
               CASE WHEN BMI_FNL >= 30 THEN 'Obese (BMI >= 30)'
                    WHEN OVERWEIGHT = 'Y' AND CO_MORBID IS NOT NULL THEN 'Overweight with comorbid'
                    ELSE ' ' END AS CAT,
               CASE WHEN REQUEST_REASON_DESCRIPTION = 'Reauthorization' THEN 'REAUTH' ELSE 'NEW START' END AS NEW_REAUTH,
               SUM(CASE WHEN CASE_STATUS = 'APPROVED' THEN 1 ELSE 0 END) AS APPRVD_CNT,
               COUNT(DISTINCT CASE_NUMBER) AS CNT,
               SUM(CASE WHEN CASE_STATUS = 'APPROVED' THEN 1 ELSE 0 END) / COUNT(DISTINCT CASE_NUMBER) AS APPRVD_PERC
        FROM BMI_TMP
        GROUP BY drug_type1,
                 CASE WHEN BMI_FNL >= 30 THEN 'Obese (BMI >= 30)'
                      WHEN OVERWEIGHT = 'Y' AND CO_MORBID IS NOT NULL THEN 'Overweight with comorbid'
                      ELSE ' ' END,
                 CASE WHEN REQUEST_REASON_DESCRIPTION = 'Reauthorization' THEN 'REAUTH' ELSE 'NEW START' END
        HAVING CASE WHEN BMI_FNL >= 30 THEN 'Obese (BMI >= 30)'
                    WHEN OVERWEIGHT = 'Y' AND CO_MORBID IS NOT NULL THEN 'Overweight with comorbid'
                    ELSE ' ' END <> ' '
    ]';

    COMMIT;
END MONTHLY_DAA74958_GLP_PA;
/
