
CREATE OR REPLACE PROCEDURE MONTHLY_DAA74957_GLP1_DUPTHERAPY AS
    PROCEDURE DROP_TABLE_IF_EXISTS(P_TABLE_NAME IN VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE 'DROP TABLE ' || DBMS_ASSERT.QUALIFIED_SQL_NAME(P_TABLE_NAME) || ' PURGE';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -942 THEN RAISE; END IF;
    END;
BEGIN
    DROP_TABLE_IF_EXISTS('DRUG_TYPE');
    DROP_TABLE_IF_EXISTS('RAWDATA');
    DROP_TABLE_IF_EXISTS('MBR_SUM_BASE');
    DROP_TABLE_IF_EXISTS('MBR_SUM');
    DROP_TABLE_IF_EXISTS('MBR_GLP');
    DROP_TABLE_IF_EXISTS('CLMS_CONCUR');
    DROP_TABLE_IF_EXISTS('CLM_RPTOUT');
    DROP_TABLE_IF_EXISTS('MBR_SUM_RPTOUT');
    DROP_TABLE_IF_EXISTS('CLM_SUM_RPTOUT');

    /* Target Drugs */
    EXECUTE IMMEDIATE q'[
        CREATE TABLE DRUG_TYPE AS
        SELECT SUBSTR(GENERIC_PRODUCT_ID,1,10) AS GPI10,
               SUBSTR(GENERIC_PRODUCT_ID,1,12) AS GPI12,
               'Drug Type 1' AS drug_type1,
               'Drug Type2' AS drug_type2
        FROM A.R12_DIAB_DRUGS
    ]';

    /* Pull claim data */
    EXECUTE IMMEDIATE q'[
        CREATE TABLE RAWDATA AS
        SELECT DISTINCT
            B.drug_type1,
            B.drug_type2,
            A.*
        FROM (
            SELECT DISTINCT
                CASE WHEN LENGTH(CD.MEMBER_ID) = 9 THEN CD.MEMBER_ID || '00'
                     WHEN SUBSTRING(CD.MEMBER_ID,1,7) = '0000000' THEN SUBSTRING(CD.MEMBER_ID,8,11)
                     ELSE CD.MEMBER_ID END AS MEMBER_ID,
                CD.LOB,
                CD.DATE_FILLED,
                CD.CLAIM_NUMBER,
                CD.LOB2,
                CD.LOB3,
                CD.DRUG_NDC AS NDC,
                CD.DRUG_LABEL_NAME AS LABEL_NAME,
                CD.DRUG_BRAND_NAME AS BRAND_NAME,
                CD.RX_COUNT AS RXS,
                CD.CLAIM_PLAN_DAYS_SUPPLY AS DAYS,
                CD.CLAIM_PLAN_MET_DEC_QTY AS QTY,
                CD.AMT_PLAN_ING_COST AS ING_COST,
                CD.AMT_PLAN_DISP_FEE AS DISP_FEE,
                CD.AMT_TOTAL_COST AS ALLOWED,
                CD.AMT_MEMBER_COPAY AS COPAY,
                CD.AMT_MEMBER_DED_COST AS DEDUCT,
                CD.AMT_MEMBER_LIAB AS MBR_COST,
                CD.AMT_PLAN_PAID AS PLAN_PAID,
                SUBSTRING(CD.GENERIC_PRODUCT_ID,1,10) AS GPI10,
                SUBSTRING(CD.GENERIC_PRODUCT_ID,1,12) AS GPI12,
                CD.GENERIC_PRODUCT_ID AS GPI14
            FROM CLAIM_DETAIL_PAID CD
            WHERE CD.DATE_FILLED BETWEEN DATE '2022-01-01' AND LAST_DAY(ADD_MONTHS(TRUNC(SYSDATE,'MM'),-1))
              AND CD.DRUG_NDC IN (
                  SELECT NDC
                  FROM RX_DATA.MEDISPAN
                  WHERE GPI10 IN ('2717005600','2717002000','2717308000','2717007000','6125205000','2717001500','2717005000','6125207000')
              )
              AND CD.CLAIM_CICS_STATUS_CODE NOT IN ('HIS','HRV')
        ) A
        LEFT JOIN DRUG_TYPE B
          ON A.GPI12 = B.GPI12
    ]';

    /* MBR SUMMARY */
    EXECUTE IMMEDIATE q'[
        CREATE TABLE MBR_SUM_BASE AS
        SELECT A.MEMBER_ID,
               CASE WHEN A.LOB = 'PHP CMC' THEN 'Medicare' ELSE A.LOB END AS LOB,
               CASE WHEN D.MEMBER_ID IS NOT NULL THEN 'Y' ELSE 'N' END AS DM_ONLY,
               CASE WHEN DW.MEMBER_ID IS NOT NULL THEN 'Y' ELSE 'N' END AS DM_W_WL,
               CASE WHEN W.MEMBER_ID IS NOT NULL THEN 'Y' ELSE 'N' END AS WL_ONLY,
               MAX(DATE_FILLED) AS MAX_FILL
        FROM RAWDATA A
        LEFT JOIN (SELECT DISTINCT MEMBER_ID FROM RAWDATA WHERE drug_type1 = 'GLP-1: DM ONLY') D
          ON A.MEMBER_ID = D.MEMBER_ID
        LEFT JOIN (SELECT DISTINCT MEMBER_ID FROM RAWDATA WHERE drug_type1 = 'GLP-1: DM w WL') DW
          ON A.MEMBER_ID = DW.MEMBER_ID
        LEFT JOIN (SELECT DISTINCT MEMBER_ID FROM RAWDATA WHERE drug_type1 = 'GLP-1: WL only') W
          ON A.MEMBER_ID = W.MEMBER_ID
        GROUP BY A.MEMBER_ID,
                 CASE WHEN A.LOB = 'PHP CMC' THEN 'Medicare' ELSE A.LOB END,
                 CASE WHEN D.MEMBER_ID IS NOT NULL THEN 'Y' ELSE 'N' END,
                 CASE WHEN DW.MEMBER_ID IS NOT NULL THEN 'Y' ELSE 'N' END,
                 CASE WHEN W.MEMBER_ID IS NOT NULL THEN 'Y' ELSE 'N' END
    ]';

    EXECUTE IMMEDIATE q'[
        CREATE TABLE MBR_SUM AS
        SELECT MEMBER_ID, LOB, DM_ONLY, DM_W_WL, WL_ONLY, MAX_FILL,
               CASE WHEN CATS(DM_ONLY,DM_W_WL,WL_ONLY) IN ('NNY','NYN','YNN') THEN 'Monotherapy'
                    WHEN CATS(DM_ONLY,DM_W_WL,WL_ONLY) IN ('NYY','YNY','YYN') THEN 'Dual Therapy'
                    WHEN CATS(DM_ONLY,DM_W_WL,WL_ONLY) IN ('YYY') THEN 'Triple Therapy' END AS UTIL,
               CASE WHEN CATS(DM_ONLY,DM_W_WL,WL_ONLY) IN ('NNY') THEN 'GLP-1: WL only'
                    WHEN CATS(DM_ONLY,DM_W_WL,WL_ONLY) IN ('NYN') THEN 'GLP-1: DM w WL'
                    WHEN CATS(DM_ONLY,DM_W_WL,WL_ONLY) IN ('YNN') THEN 'GLP-1: DM only'
                    WHEN CATS(DM_ONLY,DM_W_WL,WL_ONLY) IN ('NYY') THEN 'GLP-1: DM w WL + GLP-1: WL only'
                    WHEN CATS(DM_ONLY,DM_W_WL,WL_ONLY) IN ('YNY') THEN 'GLP-1: DM only + GLP-1: WL only'
                    WHEN CATS(DM_ONLY,DM_W_WL,WL_ONLY) IN ('YYN') THEN 'GLP-1: DM only + GLP-1: DM w WL'
                    WHEN CATS(DM_ONLY,DM_W_WL,WL_ONLY) IN ('YYY') THEN 'All GLP1' END AS THER
        FROM (
            SELECT MB.*, ROW_NUMBER() OVER (PARTITION BY MEMBER_ID ORDER BY MAX_FILL DESC) AS RN
            FROM MBR_SUM_BASE MB
        )
        WHERE RN = 1
    ]';

    /* Concurrent GLP1 members */
    EXECUTE IMMEDIATE q'[
        CREATE TABLE MBR_GLP AS
        SELECT MEMBER_ID, drug_type1, SUM(RXS) AS RXS
        FROM RAWDATA
        GROUP BY MEMBER_ID, drug_type1
    ]';

    EXECUTE IMMEDIATE q'[
        CREATE TABLE CLMS_CONCUR AS
        WITH BASE AS (
            SELECT R.*,
                   ROW_NUMBER() OVER (PARTITION BY MEMBER_ID ORDER BY DATE_FILLED) AS MBR_NO,
                   LAG(drug_type2) OVER (PARTITION BY MEMBER_ID ORDER BY DATE_FILLED) AS DRG_PRIOR,
                   LAG(DATE_FILLED) OVER (PARTITION BY MEMBER_ID ORDER BY DATE_FILLED) AS PRIOR_DATE,
                   LAG(DAYS) OVER (PARTITION BY MEMBER_ID ORDER BY DATE_FILLED) AS PRIOR_DAYS
            FROM RAWDATA R
            WHERE MEMBER_ID IN (SELECT MEMBER_ID FROM MBR_GLP GROUP BY MEMBER_ID HAVING COUNT(*) > 1)
        )
        SELECT BASE.*,
               PRIOR_DATE + PRIOR_DAYS AS DRG_PRIOR_END,
               CASE WHEN DRG_PRIOR IS NOT NULL AND drug_type2 <> DRG_PRIOR AND DATE_FILLED < PRIOR_DATE + PRIOR_DAYS THEN 'Y'
                    WHEN DRG_PRIOR IS NOT NULL AND drug_type2 <> DRG_PRIOR AND DATE_FILLED >= PRIOR_DATE + PRIOR_DAYS THEN 'N'
               END AS OVERLAP
        FROM BASE
    ]';

    EXECUTE IMMEDIATE q'[
        CREATE TABLE CLM_RPTOUT AS
        SELECT A.MBR_NO, A.MEMBER_ID,
               CASE WHEN C.MEMBER_ID IS NOT NULL THEN 'Concurrent GLP1s' ELSE 'Not Concurrent GLP1s' END AS GLP_OVERLAP,
               B.THER, B.LOB,
               A.drug_type1, A.drug_type2, A.OVERLAP, A.DRG_PRIOR, A.DRG_PRIOR_END, A.DATE_FILLED, A.DAYS,
               A.*
        FROM CLMS_CONCUR A
        LEFT JOIN MBR_SUM B ON A.MEMBER_ID = B.MEMBER_ID
        LEFT JOIN (SELECT DISTINCT MEMBER_ID FROM CLMS_CONCUR WHERE OVERLAP = 'Y') C
          ON A.MEMBER_ID = C.MEMBER_ID
        ORDER BY MEMBER_ID, DATE_FILLED
    ]';

    EXECUTE IMMEDIATE q'[
        CREATE TABLE MBR_SUM_RPTOUT AS
        SELECT CASE WHEN UTIL='Monotherapy' THEN 1 WHEN UTIL='Dual Therapy' THEN 2 WHEN UTIL='Triple Therapy' THEN 3 END AS INT_ORDER,
               UTIL, DM_ONLY, DM_W_WL, WL_ONLY, LOB,
               COUNT(DISTINCT MEMBER_ID) AS MBRS
        FROM MBR_SUM
        GROUP BY CASE WHEN UTIL='Monotherapy' THEN 1 WHEN UTIL='Dual Therapy' THEN 2 WHEN UTIL='Triple Therapy' THEN 3 END,
                 UTIL, DM_ONLY, DM_W_WL, WL_ONLY, LOB
    ]';

    EXECUTE IMMEDIATE q'[
        CREATE TABLE CLM_SUM_RPTOUT AS
        SELECT LOB, GLP_OVERLAP, THER,
               COUNT(DISTINCT MEMBER_ID) AS MBRS,
               SUM(RXS) AS RXS,
               SUM(ALLOWED) AS ALLOWED,
               SUM(PLAN_PAID) AS PAID
        FROM CLM_RPTOUT
        GROUP BY LOB, GLP_OVERLAP, THER
    ]';

    COMMIT;
END MONTHLY_DAA74957_GLP1_DUPTHERAPY;
/
